[package]
name = "pocket-web-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"]  }
futures = { version = "0.3", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
ulid = { version = "1.2.1", features = ["serde"] }
warp = { version = "0.3.7", features = ["tls"] }


[build-dependencies]
cmake = "0.1.54"
bindgen = "0.71.1"
