[package]
name = "pocket-web-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"]  }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
warp = { version = "0.3.7", features = ["tls"] }
jsonwebtoken = "9"

[build-dependencies]
cmake = "0.1.54"
bindgen = "0.71.1"
